#### Load Dataset & Basic Data Exploration

In [ ]:
import pandas as pd
import numpy as np

# Load dataset
file_path = "adult_with_headers (1).csv"
df = pd.read_csv(file_path)

# Display rows
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
# dataset Overview
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [ ]:
# Summary statistics
df.describe(include='all')

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
count,32561.000000,32561,3.256100e+04,32561,32561.000000,32561,32561,32561,32561,32561,32561.000000,32561.000000,32561.000000,32561,32561
unique,NaN,9,NaN,16,NaN,7,15,6,5,2,NaN,NaN,NaN,42,2
top,NaN,Private,NaN,HS-grad,NaN,Married-civ-spouse,Prof-specialty,Husband,White,Male,NaN,NaN,NaN,United-States,<=50K
freq,NaN,22696,NaN,10501,NaN,14976,4140,13193,27816,21790,NaN,NaN,NaN,29170,24720
mean,38.581647,NaN,1.897784e+05,NaN,10.080679,NaN,NaN,NaN,NaN,NaN,1077.648844,87.303830,40.437456,NaN,NaN
std,13.640433,NaN,1.055500e+05,NaN,2.572720,NaN,NaN,NaN,NaN,NaN,7385.292085,402.960219,12.347429,NaN,NaN
min,17.000000,NaN,1.228500e+04,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000,NaN,NaN
25%,28.000000,NaN,1.178270e+05,NaN,9.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,40.000000,NaN,NaN
50%,37.000000,NaN,1.783560e+05,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,40.000000,NaN,NaN
75%,48.000000,NaN,2.370510e+05,NaN,12.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,45.000000,NaN,NaN
max,90.000000,NaN,1.484705e+06,NaN,16.000000,NaN,NaN,NaN,NaN,NaN,99999.000000,4356.000000,99.000000,NaN,NaN

In [ ]:
# Check Missing values
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [ ]:
# Replace '?' with NaN
df.replace('?', np.nan, inplace=True)

# Recheck missing values
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

#### Handling Missing Values

In [ ]:
# Import required libraries
import pandas as pd
import numpy as np

#  Load the dataset
file_path = "adult_with_headers (1).csv"
df = pd.read_csv(file_path)

# Display initial shape
print("Initial dataset shape:", df.shape)

#  Replace '?' with NaN
df.replace('?', np.nan, inplace=True)

#  Check missing values BEFORE imputation
print("\nMissing values before imputation:")
print(df.isnull().sum())

# Separate numerical and categorical columns
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

print("\nNumerical Columns:")
print(list(num_cols))

print("\nCategorical Columns:")
print(list(cat_cols))

#  Impute numerical columns with MEDIAN
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

#  Impute categorical columns with MODE
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

#  Verify missing values AFTER imputation
print("\nMissing values after imputation:")
print(df.isnull().sum())

#  Final dataset info
print("\nFinal dataset info:")
print(df.info())

Initial dataset shape: (32561, 15)

Missing values before imputation:
age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

Numerical Columns:
['age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss', 'hours_per_week']

Categorical Columns:
['workclass', 'education', 'marital_status', 'occupation', 'relationship', 'race', 'sex', 'native_country', 'income']

Missing values after imputation:
age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

Final dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB
None

In [ ]:
# Scaling Numerical Features
# Standard Scaling
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
df_std_scaled = df.copy()
df_std_scaled[num_cols] = std_scaler.fit_transform(df[num_cols])

#  Display results
print("Standard Scaled Numerical Features:")
print(df_std_scaled[num_cols].head())

#  Verify mean ≈ 0 and std ≈ 1
print("\nMean of scaled features:")
print(df_std_scaled[num_cols].mean())

print("\nStandard deviation of scaled features:")
print(df_std_scaled[num_cols].std())

Standard Scaled Numerical Features:
        age    fnlwgt  education_num  capital_gain  capital_loss  \
0  0.030671 -1.063611       1.134739      0.148453      -0.21666
1  0.837109 -1.008707       1.134739     -0.145920      -0.21666
2 -0.042642  0.245079      -0.420060     -0.145920      -0.21666
3  1.057047  0.425801      -1.197459     -0.145920      -0.21666
4 -0.775768  1.408176       1.134739     -0.145920      -0.21666

   hours_per_week
0       -0.035429
1       -2.222153
2       -0.035429
3       -0.035429
4       -0.035429

Mean of scaled features:
age              -2.705915e-17
fnlwgt           -1.001625e-16
education_num     1.471887e-16
capital_gain      1.309314e-17
capital_loss      1.016900e-16
hours_per_week   -1.549355e-17
dtype: float64

Standard deviation of scaled features:
age               1.000015
fnlwgt            1.000015
education_num     1.000015
capital_gain      1.000015
capital_loss      1.000015
hours_per_week    1.000015
dtype: float64

In [ ]:
# Min-Max Scaling
from sklearn.preprocessing import MinMaxScaler

mm_scaler = MinMaxScaler()
df_mm_scaled = df.copy()
df_mm_scaled[num_cols] = mm_scaler.fit_transform(df[num_cols])

 # Apply Min-Max Scaling
mm_scaler = MinMaxScaler()
df_mm_scaled = df.copy()
df_mm_scaled[num_cols] = mm_scaler.fit_transform(df[num_cols])

# Display scaled numerical features
print("Min-Max Scaled Numerical Features (0–1 range):")
print(df_mm_scaled[num_cols].head())

# Verify min and max values
print("\nMinimum values after scaling:")
print(df_mm_scaled[num_cols].min())

print("\nMaximum values after scaling:")
print(df_mm_scaled[num_cols].max())

Min-Max Scaled Numerical Features (0–1 range):
        age    fnlwgt  education_num  capital_gain  capital_loss  \
0  0.301370  0.044302       0.800000       0.02174           0.0
1  0.452055  0.048238       0.800000       0.00000           0.0
2  0.287671  0.138113       0.533333       0.00000           0.0
3  0.493151  0.151068       0.400000       0.00000           0.0
4  0.150685  0.221488       0.800000       0.00000           0.0

   hours_per_week
0        0.397959
1        0.122449
2        0.397959
3        0.397959
4        0.397959

Minimum values after scaling:
age               0.0
fnlwgt            0.0
education_num     0.0
capital_gain      0.0
capital_loss      0.0
hours_per_week    0.0
dtype: float64

Maximum values after scaling:
age               1.0
fnlwgt            1.0
education_num     1.0
capital_gain      1.0
capital_loss      1.0
hours_per_week    1.0
dtype: float64

In [ ]:
# Comparison
# | Scaling Method | When to Use                            |
# | StandardScaler | Normal distribution, no fixed bounds   |
# | MinMaxScaler   | Neural networks, distance-based models |

#### Encoding Techniques

In [ ]:
# Create cardinality table for categorical variables
cardinality_df = pd.DataFrame({
    'Column Name': cat_cols,
    'Unique Categories': [df[col].nunique() for col in cat_cols]
}).sort_values(by='Unique Categories')

# Display cardinality table
print("\nCategorical Variable Cardinality:")
print(cardinality_df)

#  Separate low and high cardinality variables
low_cardinality = cardinality_df[
    cardinality_df['Unique Categories'] < 5
]['Column Name'].tolist()

high_cardinality = cardinality_df[
    cardinality_df['Unique Categories'] >= 5
]['Column Name'].tolist()

#  Display results clearly
print("\nLow Cardinality Categorical Variables (<5 categories):")
print(low_cardinality)
print("\nHigh Cardinality Categorical Variables (≥5 categories):")
print(high_cardinality)

Categorical Variable Cardinality:
      Column Name  Unique Categories
6             sex                  2
8          income                  2
5            race                  5
4    relationship                  6
2  marital_status                  7
0       workclass                  9
3      occupation                 15
1       education                 16
7  native_country                 42

Low Cardinality Categorical Variables (<5 categories):
['sex', 'income']

High Cardinality Categorical Variables (≥5 categories):
['race', 'relationship', 'marital_status', 'workclass', 'occupation', 'education', 'native_country']

In [ ]:
# One Hot Encoding
# Import libraries
import pandas as pd
import numpy as np
cardinality_df = pd.DataFrame({
    'Column': cat_cols,
    'Unique_Values': [df[col].nunique() for col in cat_cols]
})

low_cardinality = cardinality_df[
    cardinality_df['Unique_Values'] < 5
]['Column'].tolist()

print("Low-cardinality categorical columns (<5 categories):")
print(low_cardinality)

# Apply One-Hot Encoding (ONLY ONCE)
df_ohe = pd.get_dummies(df, columns=low_cardinality, drop_first=True)

# Show output clearly
print("\nShape before One-Hot Encoding:", df.shape)
print("Shape after One-Hot Encoding:", df_ohe.shape)

new_columns = list(set(df_ohe.columns) - set(df.columns))
print("\nNew columns created by One-Hot Encoding:")
print(new_columns)

print("\nSample rows of encoded dataset:")
print(df_ohe.head())

Low-cardinality categorical columns (<5 categories):
['sex', 'income']

Shape before One-Hot Encoding: (32561, 15)
Shape after One-Hot Encoding: (32561, 15)

New columns created by One-Hot Encoding:
['income_ >50K', 'sex_ Male']

Sample rows of encoded dataset:
   age          workclass  fnlwgt   education  education_num  \
0   39          State-gov   77516   Bachelors             13
1   50   Self-emp-not-inc   83311   Bachelors             13
2   38            Private  215646     HS-grad              9
3   53            Private  234721        11th              7
4   28            Private  338409   Bachelors             13

        marital_status          occupation    relationship    race  \
0        Never-married        Adm-clerical   Not-in-family   White
1   Married-civ-spouse     Exec-managerial         Husband   White
2             Divorced   Handlers-cleaners   Not-in-family   White
3   Married-civ-spouse   Handlers-cleaners         Husband   Black
4   Married-civ-spouse      Prof-specialty            Wife   Black

   capital_gain  capital_loss  hours_per_week  native_country  sex_ Male  \
0          2174             0              40   United-States       True
1             0             0              13   United-States       True
2             0             0              40   United-States       True
3             0             0              40   United-States       True
4             0             0              40            Cuba      False

   income_ >50K
0         False
1         False
2         False
3         False
4         False

In [ ]:
# Label Encoding (Categories ≥ 5)
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for col in high_cardinality:
    df[col] = le.fit_transform(df[col])

# Apply Label Encoding
le = LabelEncoder()

for col in high_cardinality:
    df[col] = le.fit_transform(df[col])

print("\nData types after Label Encoding:")
print(df[high_cardinality].dtypes)

print("\nSample rows after Label Encoding:")
print(df[high_cardinality].head())

Data types after Label Encoding:
race              int64
relationship      int64
marital_status    int64
workclass         int64
occupation        int64
education         int64
native_country    int64
dtype: object

Sample rows after Label Encoding:
   race  relationship  marital_status  workclass  occupation  education  \
0     4             1               4          7           1          9
1     4             0               2          6           4          9
2     4             1               0          4           6         11
3     2             0               2          4           6          1
4     2             5               2          4          10          9

   native_country
0              39
1              39
2              39
3              39
4               5

In [ ]:
# | Encoding | Pros                  | Cons                |
# | One-Hot  | No ordinal assumption | High dimensionality |
# | Label    | Memory efficient      | Implies false order |

#### Feature Engineering

In [ ]:
# Work experience Intensity
# Find the correct hours column
hours_col = [col for col in df.columns if 'hour' in col.lower()][0]
print("Using column:", hours_col)

# Create new feature
df['hours_per_year'] = df[hours_col] * 52

# Display output
print(df[['hours_per_year']].head())

# Rationale: Annual work effort better represents earning capacity.

Using column: hours_per_week
   hours_per_year
0            2080
1             676
2            2080
3            2080
4            2080

In [ ]:
# Educating Level Bucketing

print(df.columns)

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'income', 'hours_per_year'],
      dtype='object')

In [ ]:
import pandas as pd
import numpy as np

# Handle missing values
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

# PRINT ALL COLUMN NAMES (DEBUG – IMPORTANT)
print("\nAll column names in dataset:")
print(list(df.columns))

#  AUTO-DETECT education numeric column
edu_candidates = [
    col for col in df.columns
    if 'education' in col.lower() and df[col].dtype != 'object'
]

print("\nDetected education numeric column(s):", edu_candidates)

# Select the first detected column
edu_col = edu_candidates[0]

#  Create education level feature
df['education_level'] = df[edu_col].apply(
    lambda x: 'Low' if x <= 8 else 'Medium' if x <= 12 else 'High'
)

#  One-Hot Encode education_level
df = pd.get_dummies(df, columns=['education_level'], drop_first=True)
print("\nEducation level dummy variables (sample):")
print(df[['education_level_Medium']].head())

# Rationale: Groups education into meaningful income-based segments.

All column names in dataset:
['age', 'workclass', 'fnlwgt', 'education', 'education_num', 'marital_status', 'occupation', 'relationship', 'race', 'sex', 'capital_gain', 'capital_loss', 'hours_per_week', 'native_country', 'income', 'education_level_Low', 'education_level_Medium']

Detected education numeric column(s): ['education_num', 'education_level_Low', 'education_level_Medium']

Education level dummy variables (sample):
   education_level_Medium  education_level_Medium
0                   False                   False
1                   False                   False
2                    True                    True
3                   False                   False
4                   False                   False

In [ ]:
# Transformation Of Skewed Features
df[num_cols].skew().sort_values(ascending=False)

capital_gain      11.953848
capital_loss       4.594629
fnlwgt             1.446980
age                0.558743
hours_per_week     0.227643
education_num     -0.311676
dtype: float64

In [ ]:
# Find the correct capital gain column
cap_gain_col = [col for col in df.columns if 'capital' in col.lower() and 'gain' in col.lower()][0]

print("Using capital gain column:", cap_gain_col)

# Apply log transformation
df['capital_gain_log'] = np.log1p(df[cap_gain_col])
print("\nOriginal vs Log-transformed capital gain:")
print(df[[cap_gain_col, 'capital_gain_log']].head())

Using capital gain column: capital_gain

Original vs Log-transformed capital gain:
   capital_gain  capital_gain_log
0      7.684784          2.161573
1      0.000000          0.000000
2      0.000000          0.000000
3      0.000000          0.000000
4      0.000000          0.000000

In [ ]:
# Final data Set
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   age                     32561 non-null  int64
 1   workclass               32561 non-null  object
 2   fnlwgt                  32561 non-null  int64
 3   education               32561 non-null  object
 4   education_num           32561 non-null  int64
 5   marital_status          32561 non-null  object
 6   occupation              32561 non-null  object
 7   relationship            32561 non-null  object
 8   race                    32561 non-null  object
 9   sex                     32561 non-null  object
 10  capital_gain            32561 non-null  float64
 11  capital_loss            32561 non-null  int64
 12  hours_per_week          32561 non-null  int64
 13  native_country          32561 non-null  object
 14  income                  32561 non-null  object
 15  education_level_Low     32561 non-null  bool
 16  education_level_Medium  32561 non-null  bool
 17  education_level_Low     32561 non-null  bool
 18  education_level_Medium  32561 non-null  bool
 19  capital_gain_log        32561 non-null  float64
dtypes: bool(4), float64(2), int64(5), object(9)
memory usage: 4.1+ MB